### ISSUE TITLE
18-asyncio/charfinder/http_charfinder.py 'Request' object has no Attribute 'GET'

### ISSUE THREAD

**Issue by caiheyao** [fluentpython/example-code#31]
the 18-asyncio-py3.7 folder doesn't have this file. 
but this file doesn't work in aiohttp3.5.4 with Python3.7.2
the Request object has no attribute 'GET', use query instead.
```
def home(request):
    try:
        query = request.GET.get('query', '').strip()
    except AttributeError:
        query = request.query.get('query', '').strip()
    print('Query: {!r}'.format(query))
```

**Comment by wangzil88** [comment]
still not work in py3.97, should delete  'charset=UTF-8' in  'CONTENT_TYPE = 'text/html; charset=UTF-8'
